data_preprocessing:
  kaggle_dataset: elikplim/concrete-compressive-strength-data-set
  raw_data_file: data/raw/concrete_data.csv
  processed_data_dir: data/processed/
  test_size: 0.20
  random_state: 42
training:
  train_data_path: data/processed/train.csv
  test_data_path: data/processed/test.csv
  output_model_path: models/
  mlflow_tracking_uri: https://dagshub.com/<username>/<repo_name>.mlflow
  mlflow_experiment_name: Regression Training